######################################################################
# GitLab CI build script for the Kafka WebSocket Proxy                    #
######################################################################

######################################################################
# Shared environment variables for different stages of the CI pipeline #
######################################################################
variables:
  CI: "true"
  # Shared settings for the docker processes
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"
  # Container scanning properties
  CS_MAJOR_VERSION: 2
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/server
  CI_APPLICATION_TAG: $CI_COMMIT_SHA
  ################################################################################
  # The flags defined below can be triggered by passing in a git push option to set
  # the ci.variable.
  # Example: git push -o ci.variable="TEST_DOCKER_BUILD=true" origin <branch>
  ################################################################################
  # Flag to trigger manual publishing of pages
  MANUAL_PUBLISH_PAGES: "false"
  # Flag to trigger a test-run of the docker image build
  TEST_DOCKER_BUILD: "false"
  # Flag to trigger release
  DO_RELEASE_PREP: "false"
  # Flag to trigger test run of the release steps
  TEST_DO_RELEASE_PREP: "false"
  # Flag to allow testing of the release pipeline without publishing the docker images
  SKIP_PUBLISH: "false"

cache:
  untracked: true
  paths:
    - cache

stages:
  - prepare-release
  - commit
  - build
  - test
  - publish-docker
  - deploy
  - scan

include:
  # Release job definitions
  - local: "/.gitlab/build_templates/gitlab-ci-release.yml"
    rules:
      - if: $TEST_DOCKER_BUILD == "true"
        when: never
      - if: $MANUAL_PUBLISH_PAGES == "true"
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DO_RELEASE_PREP == "true"
      - if: $TEST_DO_RELEASE_PREP == "true"
      - if: $CI_COMMIT_TAG =~ /^v\d.*/
  # Building and testing of Scala project
  - local: "/.gitlab/build_templates/gitlab-ci-scala-build.yml"
    rules:
      - if: $DO_RELEASE_PREP == "true" || $TEST_DO_RELEASE_PREP == "true"
        when: never
      - if: $TEST_DOCKER_BUILD == "true"
        when: never
      - if: $MANUAL_PUBLISH_PAGES == "true"
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_COMMIT_BRANCH
      - if: $CI_COMMIT_TAG =~ /^v\d.*/
  # Building of Docker images
  - local: "/.gitlab/build_templates/gitlab-ci-scala-docker.yml"
    rules:
      - if: $DO_RELEASE_PREP == "true" || $TEST_DO_RELEASE_PREP == "true"
        when: never
      - if: $MANUAL_PUBLISH_PAGES == "true"
        when: never
      - if: $SKIP_PUBLISH == "true"
        when: never
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_COMMIT_TAG =~ /^v\d.*/

  # Building and publishing documentation to GitLab Pages
  - local: "/.gitlab/build_templates/gitlab-ci-scala-pages.yml"
    rules:
      - if: $TEST_DOCKER_BUILD == "true"
        when: never
      - if: $DO_RELEASE_PREP == "true" || $TEST_DO_RELEASE_PREP == "true"
        when: never
      - if: $SKIP_PUBLISH == "true"
        when: never
      - if: $CI_COMMIT_TAG =~ /^v\d.*/
      - if: $MANUAL_PUBLISH_PAGES == "true"
  # Various GitLab project scanning features
  - local: "/.gitlab/build_templates/gitlab-ci-project-scanning.yml"
    rules:
      - if: $MANUAL_PUBLISH_PAGES == "true"
        when: never
      - if: $TEST_DOCKER_BUILD == "true"
        when: never
      - if: $DO_RELEASE_PREP == "true" || $TEST_DO_RELEASE_PREP == "true"
        when: never
      - if: $SKIP_PUBLISH == "true"
        when: never
      - if: $CI_COMMIT_BRANCH
      - if: $CI_COMMIT_TAG =~ /^v\d.*/
