################################################################################
# GitLab CI pipeline for publishing docs to pages                                      #
################################################################################
# scala-steward:off

variables:
  CI: "true"
  DOCKER_DRIVER: overlay2
  SBT_MDOCS_MODULE_DIR: '$CI_PROJECT_NAME-docs'

.pages_shared_rules:
  rules:
    # Execute only when a tag is starting with v followed by a digit
    - if: $TEST_DOCKER_BUILD == "true"
      when: never
    - if: $DO_RELEASE_PREP == "true"
      when: never
    - if: $CI_COMMIT_TAG =~ /^v\d.*/ && $MANUAL_PUBLISH_PAGES != "true"
      when: on_success
      allow_failure: true
    - if: $MANUAL_PUBLISH_PAGES == "true"
      when: manual
      allow_failure: false

pages:build:
  rules:
    - !reference [.pages_shared_rules, rules]
  stage: build
  image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13.16_jdk21
  interruptible: false
  script:
    - sbt docs/mdoc
  artifacts:
    paths:
      - $SBT_MDOCS_MODULE_DIR/target
      - website

pages:
  rules:
    - !reference [.pages_shared_rules, rules]
  stage: deploy
  image: node:18-alpine
  interruptible: false
  needs:
    - job: pages:build
      artifacts: true
  script:
    - cd website
    - yarn install
    - yarn build
    - mv ./build ../public
  artifacts:
    paths:
      - public
