################################################################################
# GitLab CI build script for Scala applications published as docker images        #
################################################################################
# scala-steward:off

variables:
  CI: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"

cache:
  untracked: true
  paths:
    - cache

check style and formatting:
  stage: build
  image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13.16_jdk21
  interruptible: true
  tags:
    - saas-linux-small-amd64
  script:
    # Ensure that the pipeline fails fast if there are issues with the
    # style or formatting
    - sbt clean scalastyle scalafmt
    - git diff --exit-code || (echo "ERROR Code formatting check failed, see differences above."; false)

compile and run test suites:
  stage: test
  image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13.16_jdk21
  interruptible: true
  tags:
    - saas-linux-small-amd64
  script:
    - sbt coverage test coverageReport
    - sbt coverageAggregate
  coverage: '/Statement coverage[A-Za-z\.*]\s*:\s*([^%]+)/'
  artifacts:
    access: 'developer'
    paths:
      - target/
      - target/scala-2.13/scoverage-report
      - target/scala-2.13/coverage-report/cobertura.xml
      - ./**/target/
      - ./**/target/test-reports/TEST-*.xml
    reports:
      junit: ./**/target/test-reports/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: target/scala-2.13/coverage-report/cobertura.xml
