################################################################################
# GitLab CI build script for Scala applications published as docker images     #
################################################################################
# scala-steward:off

variables:
  CI: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"

cache:
  untracked: true
  paths:
    - cache

publish docker containers:
  stage: publish-docker
  image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13.13_jdk21
  tags:
    - saas-linux-small-amd64
  services:
    - docker:24.0.6-dind
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker login -u kpmeen -p $DOCKERHUB_TOKEN
    - docker buildx create --name kwp-multiarch-builder-$CI_JOB_ID --driver docker-container --bootstrap --use
    - sbt docker:publish
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_TAG =~ /^v\d.*/
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
